<?php
/**
 * @file
 * Integrates the Cycle2 jQuery plugin with the Views Slideshow module.
 */

/**
 * Implements hook_library_info().
 */
function views_slideshow_cycle2_library_info() {
  $path = backdrop_get_path('module', 'views_slideshow_cycle2') . '/cycle2';
  $website = 'http://jquery.malsup.com/cycle2/';
  $version = '2.1.6';

  $libraries['cycle2'] = array(
    'title' => 'Cycle2',
    'website' => $website,
    'version' => $version,
    'js' => array(
      $path . '/jquery.cycle2.min.js' => array(),
    ),
  );
  $libraries['cycle2.carousel'] = array(
    'title' => 'Cycle2: Carousel',
    'website' => $website,
    'version' => $version,
    'js' => array(
      $path . '/jquery.cycle2.carousel.min.js' => array(),
    ),
  );
  $libraries['cycle2.flip'] = array(
    'title' => 'Cycle2: Flip',
    'website' => $website,
    'version' => $version,
    'js' => array(
      $path . '/jquery.cycle2.flip.min.js' => array(),
    ),
  );
  $libraries['cycle2.scrollVert'] = array(
    'title' => 'Cycle2: ScrollVert',
    'website' => $website,
    'version' => $version,
    'js' => array(
      $path . '/jquery.cycle2.scrollVert.min.js' => array(),
    ),
  );
  $libraries['cycle2.shuffle'] = array(
    'title' => 'Cycle2: Shuffle',
    'website' => $website,
    'version' => $version,
    'js' => array(
      $path . '/jquery.cycle2.shuffle.min.js' => array(),
    ),
  );
  $libraries['cycle2.tile'] = array(
    'title' => 'Cycle2: Tile',
    'website' => $website,
    'version' => $version,
    'js' => array(
      $path . '/jquery.cycle2.tile.min.js' => array(),
    ),
  );
  $libraries['cycle2.swipe'] = array(
    'title' => 'Cycle2: Swipe',
    'website' => $website,
    'version' => $version,
    'js' => array(
      $path . '/jquery.cycle2.swipe.min.js' => array(),
    ),
  );
  $libraries['cycle2.center'] = array(
    'title' => 'Cycle2: Centered Slides',
    'website' => $website,
    'version' => $version,
    'js' => array(
      $path . '/jquery.cycle2.center.min.js' => array(),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_theme().
 */
function views_slideshow_cycle2_theme($existing, $type, $theme, $path) {
  return array(
    'views_slideshow_cycle2_main_frame' => array(
      'variables' => array(
        'settings' => NULL,
        'vss_id' => NULL,
        'rows' => NULL,
        'view' => NULL,
      ),
      'file' => 'theme/views_slideshow_cycle2.theme.inc',
      'template' => 'theme/views-slideshow-cycle2-main-frame',
      'pattern' => 'views_slideshow_cycle2_main_frame__',
    ),
    'views_slideshow_cycle2_main_frame_slide' => array(
      'variables' => array(
        'fields' => NULL,
        'key' => NULL,
        'total' => NULL,
        'options' => NULL,
        'views_style_plugin' => NULL,
      ),
      'file' => 'theme/views_slideshow_cycle2.theme.inc',
      'template' => 'theme/views-slideshow-cycle2-main-frame-slide',
      'pattern' => 'views_slideshow_cycle2_main_frame_slide__',
    ),
  );
}
